site_name: Reservoirpy
theme:
  name: material
  palette:
    scheme: preference
    primary: white
    accent: deep purple
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
  icon:
    repo: fontawesome/brands/github

nav:
  - Home: index.md

repo_url: https://github.com/scuervo91/reservoirpy
repo_name: scuervo91/reservoirpy

plugins:
  - search
  - mkdocstrings

